add startup for dfs and yarn

diff --git a/scripts/install_hadoop b/scripts/install_hadoop
--- a/scripts/install_hadoop
+++ b/scripts/install_hadoop
@@ -199,4 +199,11 @@ sudo chmod 664 ${INSTALL_ROOT}/hadoop/etc/hadoop/yarn-site.xml || die 1 "cannot 
 # Format HDFS filesystem
 
 echo -n "hduser "
-su - hduser -c "${INSTALL_ROOT}/hadoop/bin/hadoop namenode -format"
+su - hduser -c "hadoop namenode -format" || die 1 "cannot continue ... check error messages"
+
+# Start DFS and yarn
+echo -n "hduser "
+su - hduser -c "start-dfs.sh" || die 1 "cannot continue ... check error messages"
+
+echo -n "hduser "
+su - hduser -c "start-yarn.sh"
